language: ruby
rvm:
  - 2.2.2
  - 2.1.0
  - 2.0.0

before_script:
  - sudo apt-get install check
  - git clone https://github.com/klmcarthur/trooth.git /tmp/trooth/
  - pushd
  - cd /tmp/trooth && ./configure && make && sudo make install
  - popd
